"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FileText, MoreHorizontal, Printer, Trash2, ExternalLink } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ConfirmDialog } from "@/components/app/confirm-dialog";
import { EmptyState } from "@/components/app/empty-state";
import { ErrorState } from "@/components/app/error-state";
import { useMe } from "@/components/app/me-provider";
import { PageHeader } from "@/components/app/page-header";
import { Pager } from "@/components/app/pager";
import { deleteReport, getReports, paths } from "@/lib/api-client";
import { useApi } from "@/lib/hooks/use-api";
import { useUrlParams } from "@/lib/hooks/use-url-params";
import { toastError } from "@/lib/notify";
import { reveal } from "@/lib/reveal";
import { formatDate, formatPeriod } from "@/lib/format";
import type { Paginated, ReportListItem } from "@/lib/types";
import { GenerateReportDialog } from "./generate-report-dialog";

const PAGE_SIZE = 20;

export function ReportsView() {
  const router = useRouter();
  const { searchParams, set } = useUrlParams();
  const { canEdit, isAdmin } = useMe();
  const page = Math.max(1, Number(searchParams.get("page")) || 1);
  const query = { page, pageSize: PAGE_SIZE };
  const { data, error, loading, refetch } = useApi<Paginated<ReportListItem>>(paths.reports(query), (signal) =>
    getReports(query, signal),
  );
  const [toDelete, setToDelete] = useState<ReportListItem | null>(null);
  const r = reveal(1);

  async function remove() {
    if (!toDelete) return false;
    try {
      await deleteReport(toDelete.id);
      toast.success("Report deleted.");
      refetch({ silent: true });
      return true;
    } catch (err) {
      toastError(err);
      return false;
    }
  }

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="AI4 · Voice of Customer"
        title="Reports"
        description="Leadership-ready summaries of what customers said, what changed, and what to do about it."
        actions={canEdit ? <GenerateReportDialog /> : null}
      />

      <section aria-label="Saved reports" className={`space-y-4 ${r.className}`} style={r.style}>
        {error && !data ? (
          <ErrorState error={error} onRetry={() => refetch()} />
        ) : loading || !data ? (
          <div className="surface space-y-3 p-5">
            {Array.from({ length: 5 }, (_, i) => (
              <Skeleton key={i} className="h-10 w-full" />
            ))}
          </div>
        ) : data.items.length === 0 ? (
          <div className="surface">
            <EmptyState
              icon={FileText}
              title="No reports yet"
              description={
                canEdit
                  ? "Generate your first Voice-of-Customer report from the last 7 or 30 days of feedback."
                  : "Reports appear here once an analyst or admin generates one."
              }
              action={canEdit ? <GenerateReportDialog /> : undefined}
            />
          </div>
        ) : (
          <>
            <div className="surface overflow-hidden">
              <Table>
                <TableHeader>
                  <TableRow className="hover:bg-transparent">
                    <TableHead>Title</TableHead>
                    <TableHead>Period</TableHead>
                    <TableHead>Generated by</TableHead>
                    <TableHead>Date</TableHead>
                    <TableHead className="w-12">
                      <span className="sr-only">Actions</span>
                    </TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {data.items.map((rep) => (
                    <TableRow key={rep.id} className="cursor-pointer" onClick={() => router.push(`/reports/${rep.id}`)}>
                      <TableCell className="min-w-[14rem]">
                        <Link
                          href={`/reports/${rep.id}`}
                          onClick={(e) => e.stopPropagation()}
                          className="rounded-sm font-medium hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                        >
                          {rep.title}
                        </Link>
                      </TableCell>
                      <TableCell className="whitespace-nowrap font-mono text-xs text-muted-foreground">
                        {formatPeriod(rep.periodStart, rep.periodEnd)}
                      </TableCell>
                      <TableCell className="whitespace-nowrap text-sm">{rep.generatedBy?.name ?? "Former member"}</TableCell>
                      <TableCell className="whitespace-nowrap font-mono text-xs text-muted-foreground">{formatDate(rep.createdAt)}</TableCell>
                      <TableCell onClick={(e) => e.stopPropagation()}>
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button variant="ghost" size="icon" aria-label={`Actions for ${rep.title}`}>
                              <MoreHorizontal aria-hidden="true" />
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="end">
                            <DropdownMenuItem onSelect={() => router.push(`/reports/${rep.id}`)}>
                              <ExternalLink aria-hidden="true" />
                              Open
                            </DropdownMenuItem>
                            <DropdownMenuItem onSelect={() => window.open(`/reports/${rep.id}/print`, "_blank", "noopener")}>
                              <Printer aria-hidden="true" />
                              Print
                            </DropdownMenuItem>
                            {isAdmin && (
                              <>
                                <DropdownMenuSeparator />
                                <DropdownMenuItem className="text-destructive focus:text-destructive" onSelect={() => setToDelete(rep)}>
                                  <Trash2 aria-hidden="true" />
                                  Delete
                                </DropdownMenuItem>
                              </>
                            )}
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
            <Pager
              page={data.page}
              pageSize={data.pageSize}
              total={data.total}
              totalPages={data.totalPages}
              noun="reports"
              hrefFor={(p) => `/reports?page=${p}`}
              onPageChange={(p) => set({ page: p === 1 ? null : p })}
            />
          </>
        )}
      </section>

      <ConfirmDialog
        open={toDelete !== null}
        onOpenChange={(o) => !o && setToDelete(null)}
        title="Delete this report?"
        description={<p>&ldquo;{toDelete?.title}&rdquo; will be removed for everyone in the workspace. Feedback is not affected.</p>}
        onConfirm={remove}
      />
    </div>
  );
}
